//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTeacher
    {
        public int id { get; set; }
        public string teacherName { get; set; }
        public string teacherEmail { get; set; }
        public  byte[]  teacherPicture { get; set; }
        public string teacherPicName { get; set; }
    }
}
